services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: 666127452756.dkr.ecr.eu-west-2.amazonaws.com/dev-mayds-triage-agent:latest_api_2  
    container_name: customer-triage-api
    env_file:
      - ./api/.env
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-}
      AWS_DEFAULT_REGION: ${AWS_REGION:-eu-west-2}
    ports:
      - "8000:8000"
    volumes:
      - ./api/data:/app/data
    restart: unless-stopped

  ui:
    build:
      context: ./ui
    image: 666127452756.dkr.ecr.eu-west-2.amazonaws.com/dev-mayds-triage-agent:latest_ui_2
    container_name: customer-triage-ui
    environment:
      - API_URL=http://api:8000
    ports:
      - "8501:8501"
    volumes:
      - ./evals:/app/evals
    depends_on:
      - api
    restart: unless-stopped
